<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

final class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = $this->getAllProducts();

        foreach ($products as $productData) {
            $product = Product::create([
                'category_id' => $productData['category_id'],
                'slug' => Str::slug($productData['name_en']) . '-' . uniqid(),
                'sku' => $productData['sku'],
                'price' => $productData['price'],
                'compare_at_price' => $productData['compare_at_price'] ?? null,
                'cost' => round($productData['price'] * 0.6, 3),
                'current_stock' => $productData['stock'] ?? 100,
                'low_stock_threshold' => 10,
                'track_inventory' => true,
                'daily_production_capacity' => $productData['daily_capacity'] ?? 100,
                'lead_time_hours' => $productData['lead_time'] ?? 24,
                'is_available' => true,
                'is_featured' => $productData['is_featured'] ?? false,
                'is_taxable' => true,
                'requires_shipping' => true,
                'views_count' => 0,
                'sales_count' => 0,
            ]);

            // Add English translation
            $product->translations()->create([
                'locale' => 'en',
                'name' => $productData['name_en'],
                'short_description' => $productData['description_en'],
                'description' => $productData['description_en'],
            ]);

            // Add Arabic translation
            $product->translations()->create([
                'locale' => 'ar',
                'name' => $productData['name_ar'],
                'short_description' => $productData['description_ar'],
                'description' => $productData['description_ar'],
            ]);

            // Add placeholder images
            $product->images()->create([
                'image_url' => 'https://placehold.co/800x600/e8e8e8/666666?text=' . urlencode($productData['name_en']),
                'alt_text' => $productData['name_en'],
                'is_primary' => true,
                'sort_order' => 0,
            ]);

            // Add variants if specified
            if (isset($productData['variants']) && is_array($productData['variants'])) {
                foreach ($productData['variants'] as $index => $variantData) {
                    $product->variants()->create([
                        'name' => $variantData['name'],
                        'sku' => $product->sku . '-' . $variantData['suffix'],
                        'price' => $variantData['price'],
                        'stock' => $variantData['stock'] ?? 50,
                        'pack_quantity' => $variantData['quantity'],
                        'is_available' => true,
                        'sort_order' => $index,
                    ]);
                }
            }
        }

        $this->command->info('Products seeded: ' . count($products) . ' items with translations and variants');
    }

    private function getAllProducts(): array
    {
        return [
            // =====================================================
            // CATEGORY 1: Croissant Mini Size 30g
            // =====================================================
            [
                'category_id' => 1,
                'name_en' => 'Mini Plain Croissant',
                'name_ar' => 'ميني كرواسون سادة',
                'description_en' => 'Mini plain croissant, 30g per piece. Classic French buttery croissant in mini size.',
                'description_ar' => 'ميني كرواسون سادة، 30 جرام للقطعة. كرواسون فرنسي كلاسيكي بالزبدة بحجم صغير.',
                'sku' => 'EB-MNPC-001',
                'price' => 3.000,
                'stock' => 150,
                'daily_capacity' => 500,
                'lead_time' => 24,
                'is_featured' => true,
            ],
            [
                'category_id' => 1,
                'name_en' => 'Mini Cheese Croissant',
                'name_ar' => 'ميني كرواسون جبن',
                'description_en' => 'Mini cheese croissant, 30g per piece. Filled with savory cheese.',
                'description_ar' => 'ميني كرواسون جبن، 30 جرام للقطعة. محشو بالجبن اللذيذ.',
                'sku' => 'EB-MNCC-002',
                'price' => 3.000,
                'stock' => 150,
                'daily_capacity' => 500,
                'lead_time' => 24,
                'is_featured' => true,
            ],
            [
                'category_id' => 1,
                'name_en' => 'Mini Almond Croissant',
                'name_ar' => 'ميني كرواسون لوز',
                'description_en' => 'Mini almond croissant, 30g per piece. Filled with premium almond cream.',
                'description_ar' => 'ميني كرواسون لوز، 30 جرام للقطعة. محشو بكريمة اللوز الفاخرة.',
                'sku' => 'EB-MNAC-003',
                'price' => 3.000,
                'stock' => 120,
                'daily_capacity' => 400,
                'lead_time' => 24,
                'is_featured' => false,
            ],
            [
                'category_id' => 1,
                'name_en' => 'Mini Zatar Croissant',
                'name_ar' => 'ميني كرواسون زعتر',
                'description_en' => 'Mini zatar croissant, 30g per piece. Traditional Middle Eastern flavor.',
                'description_ar' => 'ميني كرواسون زعتر، 30 جرام للقطعة. نكهة شرق أوسطية تقليدية.',
                'sku' => 'EB-MNZC-004',
                'price' => 3.000,
                'stock' => 150,
                'daily_capacity' => 500,
                'lead_time' => 24,
                'is_featured' => true,
            ],
            [
                'category_id' => 1,
                'name_en' => 'Mini Halloumi Croissant',
                'name_ar' => 'ميني كرواسون حلوم',
                'description_en' => 'Mini halloumi croissant, 30g per piece. Filled with authentic halloumi cheese.',
                'description_ar' => 'ميني كرواسون حلوم، 30 جرام للقطعة. محشو بجبنة الحلوم الأصلية.',
                'sku' => 'EB-MNHC-005',
                'price' => 3.000,
                'stock' => 130,
                'daily_capacity' => 450,
                'lead_time' => 24,
                'is_featured' => false,
            ],
            [
                'category_id' => 1,
                'name_en' => 'Mini Chocolate Bun',
                'name_ar' => 'ميني كرواسون شوكولاتة',
                'description_en' => 'Mini chocolate bun, 30g per piece. Sweet chocolate-filled pastry.',
                'description_ar' => 'ميني كرواسون شوكولاتة، 30 جرام للقطعة. معجنات محشوة بالشوكولاتة الحلوة.',
                'sku' => 'EB-MNCB-006',
                'price' => 3.000,
                'stock' => 180,
                'daily_capacity' => 600,
                'lead_time' => 24,
                'is_featured' => true,
            ],

            // =====================================================
            // CATEGORY 2: Croissant Medium Size 55g
            // =====================================================
            [
                'category_id' => 2,
                'name_en' => 'Plain Croissant',
                'name_ar' => 'كرواسون سادة',
                'description_en' => 'Medium plain croissant, 55g per piece. Box of 100 pieces. Classic French buttery croissant.',
                'description_ar' => 'كرواسون سادة وسط، 55 جرام للقطعة. علبة 100 قطعة. كرواسون فرنسي كلاسيكي بالزبدة.',
                'sku' => 'EB-MDPC-007',
                'price' => 12.500,
                'stock' => 200,
                'daily_capacity' => 1000,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 100 pieces',
                        'suffix' => '100PCS',
                        'quantity' => 100,
                        'price' => 12.500,
                        'stock' => 200,
                    ],
                ],
            ],
            [
                'category_id' => 2,
                'name_en' => 'Cheese Croissant',
                'name_ar' => 'كرواسون جبن',
                'description_en' => 'Medium cheese croissant, 55g per piece. Box of 100 pieces. Filled with savory cheese.',
                'description_ar' => 'كرواسون جبن وسط، 55 جرام للقطعة. علبة 100 قطعة. محشو بالجبن اللذيذ.',
                'sku' => 'EB-MDCC-008',
                'price' => 13.500,
                'stock' => 180,
                'daily_capacity' => 900,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 100 pieces',
                        'suffix' => '100PCS',
                        'quantity' => 100,
                        'price' => 13.500,
                        'stock' => 180,
                    ],
                ],
            ],
            [
                'category_id' => 2,
                'name_en' => 'Brown Croissant',
                'name_ar' => 'كرواسون أسمر',
                'description_en' => 'Medium brown croissant, 55g per piece. Box of 100 pieces. Made with whole wheat flour.',
                'description_ar' => 'كرواسون أسمر وسط، 55 جرام للقطعة. علبة 100 قطعة. مصنوع من دقيق القمح الكامل.',
                'sku' => 'EB-MDBC-009',
                'price' => 12.500,
                'stock' => 150,
                'daily_capacity' => 800,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 100 pieces',
                        'suffix' => '100PCS',
                        'quantity' => 100,
                        'price' => 12.500,
                        'stock' => 150,
                    ],
                ],
            ],
            [
                'category_id' => 2,
                'name_en' => 'Zatar Croissant',
                'name_ar' => 'كرواسون زعتر',
                'description_en' => 'Medium zatar croissant, 55g per piece. Box of 100 pieces. Aromatic Middle Eastern herbs.',
                'description_ar' => 'كرواسون زعتر وسط، 55 جرام للقطعة. علبة 100 قطعة. أعشاب شرق أوسطية عطرية.',
                'sku' => 'EB-MDZC-010',
                'price' => 13.500,
                'stock' => 170,
                'daily_capacity' => 900,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 100 pieces',
                        'suffix' => '100PCS',
                        'quantity' => 100,
                        'price' => 13.500,
                        'stock' => 170,
                    ],
                ],
            ],
            [
                'category_id' => 2,
                'name_en' => 'Chocolate Bun',
                'name_ar' => 'كرواسون شوكولاتة',
                'description_en' => 'Medium chocolate bun, 55g per piece. Box of 100 pieces. Rich chocolate-filled pastry.',
                'description_ar' => 'كرواسون شوكولاتة وسط، 55 جرام للقطعة. علبة 100 قطعة. معجنات غنية محشوة بالشوكولاتة.',
                'sku' => 'EB-MDCB-011',
                'price' => 13.500,
                'stock' => 200,
                'daily_capacity' => 1000,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 100 pieces',
                        'suffix' => '100PCS',
                        'quantity' => 100,
                        'price' => 13.500,
                        'stock' => 200,
                    ],
                ],
            ],

            // =====================================================
            // CATEGORY 3: Croissant Jumbo Size 120g
            // =====================================================
            [
                'category_id' => 3,
                'name_en' => 'Jumbo Plain Croissant',
                'name_ar' => 'جامبو كرواسون سادة',
                'description_en' => 'Jumbo plain croissant, 120g per piece. Box of 50 pieces. Extra-large premium croissant.',
                'description_ar' => 'جامبو كرواسون سادة، 120 جرام للقطعة. علبة 50 قطعة. كرواسون فاخر بحجم كبير جداً.',
                'sku' => 'EB-JMPC-012',
                'price' => 12.500,
                'stock' => 100,
                'daily_capacity' => 400,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 12.500,
                        'stock' => 100,
                    ],
                ],
            ],
            [
                'category_id' => 3,
                'name_en' => 'Jumbo Cheese Croissant',
                'name_ar' => 'جامبو كرواسون جبن',
                'description_en' => 'Jumbo cheese croissant, 120g per piece. Box of 50 pieces. Generously filled with cheese.',
                'description_ar' => 'جامبو كرواسون جبن، 120 جرام للقطعة. علبة 50 قطعة. محشو بسخاء بالجبن.',
                'sku' => 'EB-JMCC-013',
                'price' => 13.500,
                'stock' => 90,
                'daily_capacity' => 350,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 13.500,
                        'stock' => 90,
                    ],
                ],
            ],
            [
                'category_id' => 3,
                'name_en' => 'Jumbo Almond Croissant',
                'name_ar' => 'جامبو كرواسون لوز',
                'description_en' => 'Jumbo almond croissant, 120g per piece. Box of 50 pieces. Filled with premium almond cream.',
                'description_ar' => 'جامبو كرواسون لوز، 120 جرام للقطعة. علبة 50 قطعة. محشو بكريمة اللوز الفاخرة.',
                'sku' => 'EB-JMAC-014',
                'price' => 22.500,
                'stock' => 70,
                'daily_capacity' => 250,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 22.500,
                        'stock' => 70,
                    ],
                ],
            ],
            [
                'category_id' => 3,
                'name_en' => 'Jumbo Zatar Croissant',
                'name_ar' => 'جامبو كرواسون زعتر',
                'description_en' => 'Jumbo zatar croissant, 120g per piece. Box of 50 pieces. Traditional flavor in jumbo size.',
                'description_ar' => 'جامبو كرواسون زعتر، 120 جرام للقطعة. علبة 50 قطعة. نكهة تقليدية بحجم جامبو.',
                'sku' => 'EB-JMZC-015',
                'price' => 13.500,
                'stock' => 85,
                'daily_capacity' => 300,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 13.500,
                        'stock' => 85,
                    ],
                ],
            ],
            [
                'category_id' => 3,
                'name_en' => 'Jumbo Chocolate Bun',
                'name_ar' => 'جامبو كرواسون شوكولاتة',
                'description_en' => 'Jumbo chocolate bun, 120g per piece. Box of 50 pieces. Extra chocolate in every bite.',
                'description_ar' => 'جامبو كرواسون شوكولاتة، 120 جرام للقطعة. علبة 50 قطعة. شوكولاتة إضافية في كل قضمة.',
                'sku' => 'EB-JMCB-016',
                'price' => 13.500,
                'stock' => 100,
                'daily_capacity' => 400,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 13.500,
                        'stock' => 100,
                    ],
                ],
            ],

            // =====================================================
            // CATEGORY 4: Croissant Rolls & Danish
            // =====================================================
            [
                'category_id' => 4,
                'name_en' => 'Raisin Roll',
                'name_ar' => 'رولا الزبيب',
                'description_en' => 'Raisin roll, 70g per piece. Box of 100 pieces. Sweet roll filled with plump raisins.',
                'description_ar' => 'رولا الزبيب، 70 جرام للقطعة. علبة 100 قطعة. رول حلو محشو بالزبيب الممتلئ.',
                'sku' => 'EB-RSRL-017',
                'price' => 13.500,
                'stock' => 120,
                'daily_capacity' => 800,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 100 pieces',
                        'suffix' => '100PCS',
                        'quantity' => 100,
                        'price' => 13.500,
                        'stock' => 120,
                    ],
                ],
            ],
            [
                'category_id' => 4,
                'name_en' => 'Chocolate Roll',
                'name_ar' => 'رولا الشوكولاتة',
                'description_en' => 'Chocolate roll, 70g per piece. Box of 100 pieces. Delicious chocolate swirl pastry.',
                'description_ar' => 'رولا الشوكولاتة، 70 جرام للقطعة. علبة 100 قطعة. معجنات لذيذة بلفات الشوكولاتة.',
                'sku' => 'EB-CHRL-018',
                'price' => 13.500,
                'stock' => 140,
                'daily_capacity' => 900,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 100 pieces',
                        'suffix' => '100PCS',
                        'quantity' => 100,
                        'price' => 13.500,
                        'stock' => 140,
                    ],
                ],
            ],
            [
                'category_id' => 4,
                'name_en' => 'Cinnamon & Walnuts Roll',
                'name_ar' => 'رولا القرفة والجوز',
                'description_en' => 'Cinnamon & walnuts roll, 70g per piece. Box of 100 pieces. Aromatic cinnamon with crunchy walnuts.',
                'description_ar' => 'رولا القرفة والجوز، 70 جرام للقطعة. علبة 100 قطعة. قرفة عطرية مع جوز مقرمش.',
                'sku' => 'EB-CNRL-019',
                'price' => 18.000,
                'stock' => 100,
                'daily_capacity' => 600,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 100 pieces',
                        'suffix' => '100PCS',
                        'quantity' => 100,
                        'price' => 18.000,
                        'stock' => 100,
                    ],
                ],
            ],
            [
                'category_id' => 4,
                'name_en' => 'Rectangular Danish',
                'name_ar' => 'عجينة دانش مستطيلة',
                'description_en' => 'Rectangular Danish, 80g per piece. Box of 100 pieces. Classic Danish pastry in rectangular shape.',
                'description_ar' => 'عجينة دانش مستطيلة، 80 جرام للقطعة. علبة 100 قطعة. معجنات دانش كلاسيكية بشكل مستطيل.',
                'sku' => 'EB-RDNS-020',
                'price' => 25.000,
                'stock' => 80,
                'daily_capacity' => 500,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 100 pieces',
                        'suffix' => '100PCS',
                        'quantity' => 100,
                        'price' => 25.000,
                        'stock' => 80,
                    ],
                ],
            ],
            [
                'category_id' => 4,
                'name_en' => 'Danish',
                'name_ar' => 'عجينة دانش',
                'description_en' => 'Danish pastry, 80g per piece. Box of 100 pieces. Traditional Danish with various fillings.',
                'description_ar' => 'عجينة دانش، 80 جرام للقطعة. علبة 100 قطعة. دانش تقليدي بحشوات متنوعة.',
                'sku' => 'EB-DNSH-021',
                'price' => 25.000,
                'stock' => 80,
                'daily_capacity' => 500,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 100 pieces',
                        'suffix' => '100PCS',
                        'quantity' => 100,
                        'price' => 25.000,
                        'stock' => 80,
                    ],
                ],
            ],

            // =====================================================
            // CATEGORY 5: Cookies Dough 55g
            // =====================================================
            [
                'category_id' => 5,
                'name_en' => 'Walnuts Chocolate Cookies Dough',
                'name_ar' => 'كوكيز الشوكولاتة والجوز',
                'description_en' => 'Walnuts chocolate cookies dough, 55g per piece. Box of 50 pieces. Ready to bake cookie dough.',
                'description_ar' => 'عجينة كوكيز الشوكولاتة والجوز، 55 جرام للقطعة. علبة 50 قطعة. عجينة كوكيز جاهزة للخبز.',
                'sku' => 'EB-WLCK-022',
                'price' => 10.000,
                'stock' => 100,
                'daily_capacity' => 500,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 10.000,
                        'stock' => 100,
                    ],
                ],
            ],
            [
                'category_id' => 5,
                'name_en' => 'Pistachio Chocolate Cookies Dough',
                'name_ar' => 'كوكيز بالفستق والشوكولاتة',
                'description_en' => 'Pistachio chocolate cookies dough, 55g per piece. Box of 50 pieces. Premium pistachio cookies.',
                'description_ar' => 'عجينة كوكيز بالفستق والشوكولاتة، 55 جرام للقطعة. علبة 50 قطعة. كوكيز فستق فاخر.',
                'sku' => 'EB-PSCK-023',
                'price' => 12.500,
                'stock' => 80,
                'daily_capacity' => 400,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 12.500,
                        'stock' => 80,
                    ],
                ],
            ],
            [
                'category_id' => 5,
                'name_en' => 'Double Chocolate Cookies Dough',
                'name_ar' => 'كوكيز بالشوكولاتة المزدوجة',
                'description_en' => 'Double chocolate cookies dough, 55g per piece. Box of 50 pieces. Rich double chocolate flavor.',
                'description_ar' => 'عجينة كوكيز بالشوكولاتة المزدوجة، 55 جرام للقطعة. علبة 50 قطعة. نكهة شوكولاتة مزدوجة غنية.',
                'sku' => 'EB-DBCK-024',
                'price' => 12.500,
                'stock' => 90,
                'daily_capacity' => 450,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 12.500,
                        'stock' => 90,
                    ],
                ],
            ],
            [
                'category_id' => 5,
                'name_en' => 'Peanut Butter Cookies Dough',
                'name_ar' => 'كوكيز زبدة الفول السوداني',
                'description_en' => 'Peanut butter cookies dough, 55g per piece. Box of 50 pieces. Classic peanut butter cookies.',
                'description_ar' => 'عجينة كوكيز زبدة الفول السوداني، 55 جرام للقطعة. علبة 50 قطعة. كوكيز زبدة الفول السوداني الكلاسيكي.',
                'sku' => 'EB-PBCK-025',
                'price' => 10.000,
                'stock' => 100,
                'daily_capacity' => 500,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 10.000,
                        'stock' => 100,
                    ],
                ],
            ],

            // =====================================================
            // CATEGORY 6: Muffins & Babka
            // =====================================================
            [
                'category_id' => 6,
                'name_en' => 'Vanilla Muffin',
                'name_ar' => 'مفن الفانيليا',
                'description_en' => 'Vanilla muffin, 140g per piece. Box of 50 pieces. Soft and moist vanilla muffins.',
                'description_ar' => 'مفن الفانيليا، 140 جرام للقطعة. علبة 50 قطعة. مفن الفانيليا الطري والرطب.',
                'sku' => 'EB-VNMF-026',
                'price' => 10.500,
                'stock' => 100,
                'daily_capacity' => 500,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 10.500,
                        'stock' => 100,
                    ],
                ],
            ],
            [
                'category_id' => 6,
                'name_en' => 'Chocolate Muffin',
                'name_ar' => 'مفن الشوكولاتة',
                'description_en' => 'Chocolate muffin, 140g per piece. Box of 50 pieces. Rich chocolate muffins.',
                'description_ar' => 'مفن الشوكولاتة، 140 جرام للقطعة. علبة 50 قطعة. مفن الشوكولاتة الغني.',
                'sku' => 'EB-CHMF-027',
                'price' => 10.500,
                'stock' => 110,
                'daily_capacity' => 550,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 10.500,
                        'stock' => 110,
                    ],
                ],
            ],
            [
                'category_id' => 6,
                'name_en' => 'Blueberry Muffin',
                'name_ar' => 'مفن التوت الأزرق',
                'description_en' => 'Blueberry muffin, 140g per piece. Box of 50 pieces. Fresh blueberries in every bite.',
                'description_ar' => 'مفن التوت الأزرق، 140 جرام للقطعة. علبة 50 قطعة. توت أزرق طازج في كل قضمة.',
                'sku' => 'EB-BLMF-028',
                'price' => 11.500,
                'stock' => 90,
                'daily_capacity' => 450,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 11.500,
                        'stock' => 90,
                    ],
                ],
            ],
            [
                'category_id' => 6,
                'name_en' => 'Cinnamon Babka',
                'name_ar' => 'بابكا القرفة',
                'description_en' => 'Cinnamon babka, 300g per piece. Traditional twisted bread with cinnamon swirls.',
                'description_ar' => 'بابكا القرفة، 300 جرام للقطعة. خبز ملفوف تقليدي بلفات القرفة.',
                'sku' => 'EB-CNBK-029',
                'price' => 1.000,
                'stock' => 60,
                'daily_capacity' => 200,
                'lead_time' => 24,
                'is_featured' => true,
            ],
            [
                'category_id' => 6,
                'name_en' => 'Zatar Babka',
                'name_ar' => 'بابكا بالزعتر',
                'description_en' => 'Zatar babka, 300g per piece. Savory twisted bread with aromatic zatar.',
                'description_ar' => 'بابكا بالزعتر، 300 جرام للقطعة. خبز ملفوف مالح بالزعتر العطري.',
                'sku' => 'EB-ZTBK-030',
                'price' => 1.000,
                'stock' => 60,
                'daily_capacity' => 200,
                'lead_time' => 24,
                'is_featured' => false,
            ],
            [
                'category_id' => 6,
                'name_en' => 'Cheese Olive Babka',
                'name_ar' => 'بابكا بالجبن والزيتون',
                'description_en' => 'Cheese olive babka, 300g per piece. Savory babka with cheese and olives.',
                'description_ar' => 'بابكا بالجبن والزيتون، 300 جرام للقطعة. بابكا مالحة بالجبن والزيتون.',
                'sku' => 'EB-COBK-031',
                'price' => 1.200,
                'stock' => 50,
                'daily_capacity' => 180,
                'lead_time' => 24,
                'is_featured' => false,
            ],

            // =====================================================
            // CATEGORY 7: Sourdough Breads 900g
            // =====================================================
            [
                'category_id' => 7,
                'name_en' => 'White Sourdough',
                'name_ar' => 'خبز ساوردو أبيض',
                'description_en' => 'White sourdough bread, 900g per loaf. Box of 7 pieces. Naturally fermented with crispy crust.',
                'description_ar' => 'خبز ساوردو أبيض، 900 جرام للرغيف. علبة 7 قطع. مخمر طبيعياً بقشرة مقرمشة.',
                'sku' => 'EB-WHSD-032',
                'price' => 0.900,
                'stock' => 150,
                'daily_capacity' => 300,
                'lead_time' => 48,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 7 pieces',
                        'suffix' => '7PCS',
                        'quantity' => 7,
                        'price' => 6.300,
                        'stock' => 150,
                    ],
                ],
            ],
            [
                'category_id' => 7,
                'name_en' => 'Norlander Sourdough',
                'name_ar' => 'خبز نورلاندر ساوردو',
                'description_en' => 'Norlander sourdough bread, 900g per loaf. Box of 7 pieces. Scandinavian-style sourdough.',
                'description_ar' => 'خبز نورلاندر ساوردو، 900 جرام للرغيف. علبة 7 قطع. ساوردو على الطريقة الإسكندنافية.',
                'sku' => 'EB-NRSD-033',
                'price' => 1.200,
                'stock' => 100,
                'daily_capacity' => 200,
                'lead_time' => 48,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 7 pieces',
                        'suffix' => '7PCS',
                        'quantity' => 7,
                        'price' => 8.400,
                        'stock' => 100,
                    ],
                ],
            ],
            [
                'category_id' => 7,
                'name_en' => 'Rye Sourdough',
                'name_ar' => 'ساوردو حبوب الجاودار',
                'description_en' => 'Rye sourdough bread, 900g per loaf. Box of 7 pieces. Dense and flavorful rye bread.',
                'description_ar' => 'ساوردو حبوب الجاودار، 900 جرام للرغيف. علبة 7 قطع. خبز الجاودار الكثيف واللذيذ.',
                'sku' => 'EB-RYSD-034',
                'price' => 1.200,
                'stock' => 90,
                'daily_capacity' => 180,
                'lead_time' => 48,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 7 pieces',
                        'suffix' => '7PCS',
                        'quantity' => 7,
                        'price' => 8.400,
                        'stock' => 90,
                    ],
                ],
            ],
            [
                'category_id' => 7,
                'name_en' => 'Wholemeal Sourdough',
                'name_ar' => 'خبز ساوردو كامل الحبوب',
                'description_en' => 'Wholemeal sourdough bread, 900g per loaf. Box of 7 pieces. Healthy whole grain sourdough.',
                'description_ar' => 'خبز ساوردو كامل الحبوب، 900 جرام للرغيف. علبة 7 قطع. ساوردو صحي من الحبوب الكاملة.',
                'sku' => 'EB-WMSD-035',
                'price' => 1.200,
                'stock' => 100,
                'daily_capacity' => 200,
                'lead_time' => 48,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 7 pieces',
                        'suffix' => '7PCS',
                        'quantity' => 7,
                        'price' => 8.400,
                        'stock' => 100,
                    ],
                ],
            ],
            [
                'category_id' => 7,
                'name_en' => 'Multi Sourdough',
                'name_ar' => 'خبز الساوردو متعدد الحبوب',
                'description_en' => 'Multi sourdough bread, 900g per loaf. Box of 7 pieces. Blend of multiple grains and seeds.',
                'description_ar' => 'خبز الساوردو متعدد الحبوب، 900 جرام للرغيف. علبة 7 قطع. مزيج من الحبوب والبذور المتعددة.',
                'sku' => 'EB-MTSD-036',
                'price' => 1.500,
                'stock' => 80,
                'daily_capacity' => 160,
                'lead_time' => 48,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 7 pieces',
                        'suffix' => '7PCS',
                        'quantity' => 7,
                        'price' => 10.500,
                        'stock' => 80,
                    ],
                ],
            ],
            [
                'category_id' => 7,
                'name_en' => 'Moringa Sourdough',
                'name_ar' => 'خبز ساوردو مورينجا',
                'description_en' => 'Moringa sourdough bread, 900g per loaf. Box of 7 pieces. Superfood sourdough with moringa.',
                'description_ar' => 'خبز ساوردو مورينجا، 900 جرام للرغيف. علبة 7 قطع. ساوردو صحي بالمورينجا.',
                'sku' => 'EB-MRSD-037',
                'price' => 1.500,
                'stock' => 70,
                'daily_capacity' => 140,
                'lead_time' => 48,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 7 pieces',
                        'suffix' => '7PCS',
                        'quantity' => 7,
                        'price' => 10.500,
                        'stock' => 70,
                    ],
                ],
            ],

            // =====================================================
            // CATEGORY 8: Ready Baked Breads
            // =====================================================
            [
                'category_id' => 8,
                'name_en' => 'White Samoon Bread',
                'name_ar' => 'خبز صمون أبيض',
                'description_en' => 'White samoon bread, 70g per piece. Box of 50 pieces. Traditional Iraqi-style bread.',
                'description_ar' => 'خبز صمون أبيض، 70 جرام للقطعة. علبة 50 قطعة. خبز عراقي تقليدي.',
                'sku' => 'EB-WHSM-038',
                'price' => 2.000,
                'stock' => 200,
                'daily_capacity' => 1000,
                'lead_time' => 12,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 2.000,
                        'stock' => 200,
                    ],
                ],
            ],
            [
                'category_id' => 8,
                'name_en' => 'Brown Samoon Bread',
                'name_ar' => 'خبز صمون أسمر',
                'description_en' => 'Brown samoon bread, 70g per piece. Box of 50 pieces. Whole wheat samoon bread.',
                'description_ar' => 'خبز صمون أسمر، 70 جرام للقطعة. علبة 50 قطعة. خبز صمون من القمح الكامل.',
                'sku' => 'EB-BRSM-039',
                'price' => 2.500,
                'stock' => 180,
                'daily_capacity' => 900,
                'lead_time' => 12,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 2.500,
                        'stock' => 180,
                    ],
                ],
            ],
            [
                'category_id' => 8,
                'name_en' => 'Sesame Samoon Bread',
                'name_ar' => 'خبز صمون بالسمسم',
                'description_en' => 'Sesame samoon bread, 70g per piece. Box of 50 pieces. Topped with sesame seeds.',
                'description_ar' => 'خبز صمون بالسمسم، 70 جرام للقطعة. علبة 50 قطعة. مغطى بحبوب السمسم.',
                'sku' => 'EB-SSSM-040',
                'price' => 2.500,
                'stock' => 180,
                'daily_capacity' => 900,
                'lead_time' => 12,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 2.500,
                        'stock' => 180,
                    ],
                ],
            ],
            [
                'category_id' => 8,
                'name_en' => 'Pavé Multigrain',
                'name_ar' => 'خبز بافيه متعدد الحبوب',
                'description_en' => 'Pavé multigrain bread, 150g per piece. Box of 60 pieces. Rustic multigrain bread.',
                'description_ar' => 'خبز بافيه متعدد الحبوب، 150 جرام للقطعة. علبة 60 قطعة. خبز ريفي متعدد الحبوب.',
                'sku' => 'EB-PVMG-041',
                'price' => 7.200,
                'stock' => 100,
                'daily_capacity' => 600,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 60 pieces',
                        'suffix' => '60PCS',
                        'quantity' => 60,
                        'price' => 7.200,
                        'stock' => 100,
                    ],
                ],
            ],
            [
                'category_id' => 8,
                'name_en' => 'Brown Panini Bread',
                'name_ar' => 'خبز بانيني أسمر',
                'description_en' => 'Brown panini bread. Box of 50 pieces. Whole wheat panini bread for sandwiches.',
                'description_ar' => 'خبز بانيني أسمر. علبة 50 قطعة. خبز بانيني من القمح الكامل للساندويشات.',
                'sku' => 'EB-BRPN-042',
                'price' => 9.500,
                'stock' => 120,
                'daily_capacity' => 600,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 9.500,
                        'stock' => 120,
                    ],
                ],
            ],
            [
                'category_id' => 8,
                'name_en' => 'White Panini Bread',
                'name_ar' => 'خبز بانيني أبيض',
                'description_en' => 'White panini bread. Box of 50 pieces. Classic white panini bread for sandwiches.',
                'description_ar' => 'خبز بانيني أبيض. علبة 50 قطعة. خبز بانيني أبيض كلاسيكي للساندويشات.',
                'sku' => 'EB-WHPN-043',
                'price' => 9.500,
                'stock' => 130,
                'daily_capacity' => 650,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 9.500,
                        'stock' => 130,
                    ],
                ],
            ],

            // =====================================================
            // CATEGORY 9: Half Baked Breads
            // =====================================================
            [
                'category_id' => 9,
                'name_en' => 'Dejuenette Bread',
                'name_ar' => 'خبز دوجونيت',
                'description_en' => 'Dejuenette bread, 100g per piece. Box of 50 pieces. Half-baked, finish at home.',
                'description_ar' => 'خبز دوجونيت، 100 جرام للقطعة. علبة 50 قطعة. نصف مخبوز، أكمل الخبز في المنزل.',
                'sku' => 'EB-DJNT-044',
                'price' => 3.000,
                'stock' => 150,
                'daily_capacity' => 700,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 3.000,
                        'stock' => 150,
                    ],
                ],
            ],
            [
                'category_id' => 9,
                'name_en' => 'Portuguese Bread',
                'name_ar' => 'خبز برتغالي',
                'description_en' => 'Portuguese bread, 55g per piece. Box of 50 pieces. Half-baked Portuguese rolls.',
                'description_ar' => 'خبز برتغالي، 55 جرام للقطعة. علبة 50 قطعة. خبز برتغالي نصف مخبوز.',
                'sku' => 'EB-PTBR-045',
                'price' => 3.000,
                'stock' => 140,
                'daily_capacity' => 700,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 3.000,
                        'stock' => 140,
                    ],
                ],
            ],
            [
                'category_id' => 9,
                'name_en' => 'Sesame Baguette',
                'name_ar' => 'خبز باغيت فرنسي بالسمسم',
                'description_en' => 'Sesame baguette. Box of 10 pieces. Half-baked French baguette with sesame seeds.',
                'description_ar' => 'خبز باغيت فرنسي بالسمسم. علبة 10 قطع. باغيت فرنسي نصف مخبوز بحبوب السمسم.',
                'sku' => 'EB-SSBG-046',
                'price' => 2.300,
                'stock' => 80,
                'daily_capacity' => 300,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 10 pieces',
                        'suffix' => '10PCS',
                        'quantity' => 10,
                        'price' => 2.300,
                        'stock' => 80,
                    ],
                ],
            ],
            [
                'category_id' => 9,
                'name_en' => 'Vienoise Bread',
                'name_ar' => 'خبز فيينواز',
                'description_en' => 'Vienoise bread, 100g per piece. Box of 50 pieces. Half-baked Viennese-style bread.',
                'description_ar' => 'خبز فيينواز، 100 جرام للقطعة. علبة 50 قطعة. خبز نصف مخبوز على الطريقة الفيينية.',
                'sku' => 'EB-VNBR-047',
                'price' => 5.000,
                'stock' => 100,
                'daily_capacity' => 500,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 50 pieces',
                        'suffix' => '50PCS',
                        'quantity' => 50,
                        'price' => 5.000,
                        'stock' => 100,
                    ],
                ],
            ],
            [
                'category_id' => 9,
                'name_en' => 'French Baguette',
                'name_ar' => 'خبز باغيت فرنسي',
                'description_en' => 'French baguette. Box of 10 pieces. Half-baked traditional French baguette.',
                'description_ar' => 'خبز باغيت فرنسي. علبة 10 قطع. باغيت فرنسي تقليدي نصف مخبوز.',
                'sku' => 'EB-FRBG-048',
                'price' => 2.300,
                'stock' => 100,
                'daily_capacity' => 400,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 10 pieces',
                        'suffix' => '10PCS',
                        'quantity' => 10,
                        'price' => 2.300,
                        'stock' => 100,
                    ],
                ],
            ],
            [
                'category_id' => 9,
                'name_en' => 'Country Baguette',
                'name_ar' => 'خبز باغيت الريفي',
                'description_en' => 'Country baguette. Box of 10 pieces. Half-baked rustic French baguette.',
                'description_ar' => 'خبز باغيت الريفي. علبة 10 قطع. باغيت فرنسي ريفي نصف مخبوز.',
                'sku' => 'EB-CTBG-049',
                'price' => 2.600,
                'stock' => 90,
                'daily_capacity' => 350,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 10 pieces',
                        'suffix' => '10PCS',
                        'quantity' => 10,
                        'price' => 2.600,
                        'stock' => 90,
                    ],
                ],
            ],

            // =====================================================
            // CATEGORY 10: Burger Buns
            // =====================================================
            [
                'category_id' => 10,
                'name_en' => 'Burger Plain Buns',
                'name_ar' => 'خبز برغر سادة',
                'description_en' => 'Burger plain buns, 100g per piece. Box of 60 pieces. Simple burger buns without toppings.',
                'description_ar' => 'خبز برغر سادة، 100 جرام للقطعة. علبة 60 قطعة. خبز برغر بسيط بدون إضافات.',
                'sku' => 'EB-BGPN-050',
                'price' => 4.800,
                'stock' => 180,
                'daily_capacity' => 1200,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 60 pieces',
                        'suffix' => '60PCS',
                        'quantity' => 60,
                        'price' => 4.800,
                        'stock' => 180,
                    ],
                ],
            ],
            [
                'category_id' => 10,
                'name_en' => 'Burger White Buns 70g',
                'name_ar' => 'خبز برغر أبيض 70 جرام',
                'description_en' => 'Burger white buns, 70g per piece. Box of 60 pieces. Classic white burger buns.',
                'description_ar' => 'خبز برغر أبيض، 70 جرام للقطعة. علبة 60 قطعة. خبز برغر أبيض كلاسيكي.',
                'sku' => 'EB-BGWH70-051',
                'price' => 3.600,
                'stock' => 180,
                'daily_capacity' => 1200,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 60 pieces',
                        'suffix' => '60PCS',
                        'quantity' => 60,
                        'price' => 3.600,
                        'stock' => 180,
                    ],
                ],
            ],
            [
                'category_id' => 10,
                'name_en' => 'Burger Sesame Buns 100g',
                'name_ar' => 'خبز برغر بالسمسم 100 جرام',
                'description_en' => 'Burger sesame buns, 100g per piece. Box of 60 pieces. Classic sesame-topped burger buns.',
                'description_ar' => 'خبز برغر بالسمسم، 100 جرام للقطعة. علبة 60 قطعة. خبز برغر كلاسيكي مغطى بالسمسم.',
                'sku' => 'EB-BGSS100-052',
                'price' => 4.800,
                'stock' => 200,
                'daily_capacity' => 1300,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 60 pieces',
                        'suffix' => '60PCS',
                        'quantity' => 60,
                        'price' => 4.800,
                        'stock' => 200,
                    ],
                ],
            ],
            [
                'category_id' => 10,
                'name_en' => 'Burger Sesame Buns 70g',
                'name_ar' => 'خبز برغر بالسمسم 70 جرام',
                'description_en' => 'Burger sesame buns, 70g per piece. Box of 60 pieces. Sesame-topped burger buns.',
                'description_ar' => 'خبز برغر بالسمسم، 70 جرام للقطعة. علبة 60 قطعة. خبز برغر مغطى بالسمسم.',
                'sku' => 'EB-BGSS70-053',
                'price' => 3.600,
                'stock' => 200,
                'daily_capacity' => 1300,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 60 pieces',
                        'suffix' => '60PCS',
                        'quantity' => 60,
                        'price' => 3.600,
                        'stock' => 200,
                    ],
                ],
            ],
            [
                'category_id' => 10,
                'name_en' => 'Mini Burger Sesame Buns',
                'name_ar' => 'خبز برغر صغير بالسمسم',
                'description_en' => 'Mini burger sesame buns, 30g per piece. Box of 160 pieces. Perfect for sliders.',
                'description_ar' => 'خبز برغر صغير بالسمسم، 30 جرام للقطعة. علبة 160 قطعة. مثالي للسلايدرز.',
                'sku' => 'EB-MNBG-054',
                'price' => 7.200,
                'stock' => 150,
                'daily_capacity' => 1600,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 160 pieces',
                        'suffix' => '160PCS',
                        'quantity' => 160,
                        'price' => 7.200,
                        'stock' => 150,
                    ],
                ],
            ],
            [
                'category_id' => 10,
                'name_en' => 'Brown Burger Buns',
                'name_ar' => 'خبز برغر أسمر',
                'description_en' => 'Brown burger buns, 70g per piece. Box of 60 pieces. Whole wheat burger buns.',
                'description_ar' => 'خبز برغر أسمر، 70 جرام للقطعة. علبة 60 قطعة. خبز برغر من القمح الكامل.',
                'sku' => 'EB-BGBR-055',
                'price' => 3.600,
                'stock' => 140,
                'daily_capacity' => 900,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 60 pieces',
                        'suffix' => '60PCS',
                        'quantity' => 60,
                        'price' => 3.600,
                        'stock' => 140,
                    ],
                ],
            ],
            [
                'category_id' => 10,
                'name_en' => 'Potato Buns',
                'name_ar' => 'خبز برغر البطاطا',
                'description_en' => 'Potato buns, 70g per piece. Box of 60 pieces. Soft burger buns made with potato.',
                'description_ar' => 'خبز برغر البطاطا، 70 جرام للقطعة. علبة 60 قطعة. خبز برغر طري مصنوع بالبطاطا.',
                'sku' => 'EB-PTBN-056',
                'price' => 4.800,
                'stock' => 130,
                'daily_capacity' => 800,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 60 pieces',
                        'suffix' => '60PCS',
                        'quantity' => 60,
                        'price' => 4.800,
                        'stock' => 130,
                    ],
                ],
            ],
            [
                'category_id' => 10,
                'name_en' => 'Brioche Buns',
                'name_ar' => 'خبز برغر بريوش',
                'description_en' => 'Brioche buns, 70g per piece. Box of 60 pieces. Premium buttery brioche burger buns.',
                'description_ar' => 'خبز برغر بريوش، 70 جرام للقطعة. علبة 60 قطعة. خبز برغر بريوش فاخر بالزبدة.',
                'sku' => 'EB-BRBN-057',
                'price' => 12.000,
                'stock' => 100,
                'daily_capacity' => 600,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 60 pieces',
                        'suffix' => '60PCS',
                        'quantity' => 60,
                        'price' => 12.000,
                        'stock' => 100,
                    ],
                ],
            ],

            // =====================================================
            // CATEGORY 11: Slice Breads 450g
            // =====================================================
            [
                'category_id' => 11,
                'name_en' => 'White Slice',
                'name_ar' => 'خبز توست أبيض',
                'description_en' => 'White slice bread, 450g per loaf. Box of 15 pieces. Classic white sandwich bread.',
                'description_ar' => 'خبز توست أبيض، 450 جرام للرغيف. علبة 15 قطعة. خبز ساندويش أبيض كلاسيكي.',
                'sku' => 'EB-WHSL-058',
                'price' => 7.500,
                'stock' => 200,
                'daily_capacity' => 400,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 15 loaves',
                        'suffix' => '15PCS',
                        'quantity' => 15,
                        'price' => 7.500,
                        'stock' => 200,
                    ],
                ],
            ],
            [
                'category_id' => 11,
                'name_en' => 'Brown Slice',
                'name_ar' => 'خبز توست أسمر',
                'description_en' => 'Brown slice bread, 450g per loaf. Box of 15 pieces. Whole wheat sandwich bread.',
                'description_ar' => 'خبز توست أسمر، 450 جرام للرغيف. علبة 15 قطعة. خبز ساندويش من القمح الكامل.',
                'sku' => 'EB-BRSL-059',
                'price' => 9.000,
                'stock' => 180,
                'daily_capacity' => 350,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 15 loaves',
                        'suffix' => '15PCS',
                        'quantity' => 15,
                        'price' => 9.000,
                        'stock' => 180,
                    ],
                ],
            ],
            [
                'category_id' => 11,
                'name_en' => 'Chia Slice',
                'name_ar' => 'خبز توست بذور الشيا',
                'description_en' => 'Chia slice bread, 450g per loaf. Box of 15 pieces. Enriched with chia seeds.',
                'description_ar' => 'خبز توست بذور الشيا، 450 جرام للرغيف. علبة 15 قطعة. مدعم بذور الشيا.',
                'sku' => 'EB-CHSL-060',
                'price' => 10.500,
                'stock' => 120,
                'daily_capacity' => 250,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 15 loaves',
                        'suffix' => '15PCS',
                        'quantity' => 15,
                        'price' => 10.500,
                        'stock' => 120,
                    ],
                ],
            ],
            [
                'category_id' => 11,
                'name_en' => 'Oats Slice',
                'name_ar' => 'خبز توست بالشوفان',
                'description_en' => 'Oats slice bread, 450g per loaf. Box of 15 pieces. Healthy bread with oats.',
                'description_ar' => 'خبز توست بالشوفان، 450 جرام للرغيف. علبة 15 قطعة. خبز صحي بالشوفان.',
                'sku' => 'EB-OTSL-061',
                'price' => 10.500,
                'stock' => 120,
                'daily_capacity' => 250,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 15 loaves',
                        'suffix' => '15PCS',
                        'quantity' => 15,
                        'price' => 10.500,
                        'stock' => 120,
                    ],
                ],
            ],
            [
                'category_id' => 11,
                'name_en' => 'Pumpkin Seeds Slice',
                'name_ar' => 'خبز توست بذور اليقطين',
                'description_en' => 'Pumpkin seeds slice bread, 450g per loaf. Box of 15 pieces. Topped with pumpkin seeds.',
                'description_ar' => 'خبز توست بذور اليقطين، 450 جرام للرغيف. علبة 15 قطعة. مغطى بذور اليقطين.',
                'sku' => 'EB-PMSL-062',
                'price' => 10.500,
                'stock' => 110,
                'daily_capacity' => 230,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 15 loaves',
                        'suffix' => '15PCS',
                        'quantity' => 15,
                        'price' => 10.500,
                        'stock' => 110,
                    ],
                ],
            ],
            [
                'category_id' => 11,
                'name_en' => 'Mix Seeds Slice',
                'name_ar' => 'خبز توست ببذور مشكلة',
                'description_en' => 'Mix seeds slice bread, 450g per loaf. Box of 15 pieces. Blend of multiple seeds.',
                'description_ar' => 'خبز توست ببذور مشكلة، 450 جرام للرغيف. علبة 15 قطعة. مزيج من بذور متعددة.',
                'sku' => 'EB-MXSL-063',
                'price' => 10.500,
                'stock' => 130,
                'daily_capacity' => 270,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 15 loaves',
                        'suffix' => '15PCS',
                        'quantity' => 15,
                        'price' => 10.500,
                        'stock' => 130,
                    ],
                ],
            ],
            [
                'category_id' => 11,
                'name_en' => 'Flax Seeds Slice',
                'name_ar' => 'خبز توست ببذور الكتان',
                'description_en' => 'Flax seeds slice bread, 450g per loaf. Box of 15 pieces. Enriched with flax seeds.',
                'description_ar' => 'خبز توست ببذور الكتان، 450 جرام للرغيف. علبة 15 قطعة. مدعم بذور الكتان.',
                'sku' => 'EB-FLSL-064',
                'price' => 10.500,
                'stock' => 110,
                'daily_capacity' => 230,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 15 loaves',
                        'suffix' => '15PCS',
                        'quantity' => 15,
                        'price' => 10.500,
                        'stock' => 110,
                    ],
                ],
            ],
            [
                'category_id' => 11,
                'name_en' => 'Sunflower Slice',
                'name_ar' => 'خبز توست ببذور دوار الشمس',
                'description_en' => 'Sunflower slice bread, 450g per loaf. Box of 15 pieces. Topped with sunflower seeds.',
                'description_ar' => 'خبز توست ببذور دوار الشمس، 450 جرام للرغيف. علبة 15 قطعة. مغطى بذور دوار الشمس.',
                'sku' => 'EB-SFSL-065',
                'price' => 10.500,
                'stock' => 110,
                'daily_capacity' => 230,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 15 loaves',
                        'suffix' => '15PCS',
                        'quantity' => 15,
                        'price' => 10.500,
                        'stock' => 110,
                    ],
                ],
            ],
            [
                'category_id' => 11,
                'name_en' => 'Sesame Slice',
                'name_ar' => 'خبز توست السمسم',
                'description_en' => 'Sesame slice bread, 450g per loaf. Box of 15 pieces. Topped with sesame seeds.',
                'description_ar' => 'خبز توست السمسم، 450 جرام للرغيف. علبة 15 قطعة. مغطى بحبوب السمسم.',
                'sku' => 'EB-SSSL-066',
                'price' => 10.500,
                'stock' => 120,
                'daily_capacity' => 250,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 15 loaves',
                        'suffix' => '15PCS',
                        'quantity' => 15,
                        'price' => 10.500,
                        'stock' => 120,
                    ],
                ],
            ],
            [
                'category_id' => 11,
                'name_en' => 'Brioche Slice',
                'name_ar' => 'خبز بريوش',
                'description_en' => 'Brioche slice bread, 450g per loaf. Box of 15 pieces. Rich, buttery brioche bread.',
                'description_ar' => 'خبز بريوش، 450 جرام للرغيف. علبة 15 قطعة. خبز بريوش غني بالزبدة.',
                'sku' => 'EB-BRSL-067',
                'price' => 10.500,
                'stock' => 140,
                'daily_capacity' => 300,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 15 loaves',
                        'suffix' => '15PCS',
                        'quantity' => 15,
                        'price' => 10.500,
                        'stock' => 140,
                    ],
                ],
            ],

            // =====================================================
            // CATEGORY 12: Paton Dough
            // =====================================================
            [
                'category_id' => 12,
                'name_en' => 'Croissant Paton',
                'name_ar' => 'عجينة باتون كرواسون',
                'description_en' => 'Croissant paton dough, 9.6kg per piece. Box of 2 pieces. Professional laminated dough.',
                'description_ar' => 'عجينة باتون كرواسون، 9.6 كيلوجرام للقطعة. علبة قطعتين. عجينة مطبقة احترافية.',
                'sku' => 'EB-CRPT-068',
                'price' => 20.000,
                'stock' => 40,
                'daily_capacity' => 80,
                'lead_time' => 48,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 2 pieces (9.6kg each)',
                        'suffix' => '2PCS',
                        'quantity' => 2,
                        'price' => 20.000,
                        'stock' => 40,
                    ],
                ],
            ],
            [
                'category_id' => 12,
                'name_en' => 'Paton of Puff',
                'name_ar' => 'باتون بف باستري',
                'description_en' => 'Paton of puff pastry, 5.5kg per piece. Box of 2 pieces. Premium puff pastry dough.',
                'description_ar' => 'باتون بف باستري، 5.5 كيلوجرام للقطعة. علبة قطعتين. عجينة بف باستري فاخرة.',
                'sku' => 'EB-PFPT-069',
                'price' => 15.000,
                'stock' => 40,
                'daily_capacity' => 80,
                'lead_time' => 48,
                'is_featured' => true,
                'variants' => [
                    [
                        'name' => 'Box of 2 pieces (5.5kg each)',
                        'suffix' => '2PCS',
                        'quantity' => 2,
                        'price' => 15.000,
                        'stock' => 40,
                    ],
                ],
            ],
            [
                'category_id' => 12,
                'name_en' => 'Pastry Sheet',
                'name_ar' => 'رقائق الفطائر',
                'description_en' => 'Pastry sheet, 8kg per piece. Box of 1 piece. Large format pastry sheets.',
                'description_ar' => 'رقائق الفطائر، 8 كيلوجرام للقطعة. علبة قطعة واحدة. رقائق فطائر بحجم كبير.',
                'sku' => 'EB-PSSH-070',
                'price' => 17.000,
                'stock' => 30,
                'daily_capacity' => 50,
                'lead_time' => 48,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => '1 piece (8kg)',
                        'suffix' => '1PC',
                        'quantity' => 1,
                        'price' => 17.000,
                        'stock' => 30,
                    ],
                ],
            ],
            [
                'category_id' => 12,
                'name_en' => 'Pie Base',
                'name_ar' => 'قاعدة فطيرة',
                'description_en' => 'Pie base dough, 5kg per piece. Box of 5 pieces. Ready-to-use pie dough base.',
                'description_ar' => 'قاعدة فطيرة، 5 كيلوجرام للقطعة. علبة 5 قطع. قاعدة عجينة فطيرة جاهزة للاستخدام.',
                'sku' => 'EB-PIBS-071',
                'price' => 7.500,
                'stock' => 50,
                'daily_capacity' => 100,
                'lead_time' => 48,
                'is_featured' => false,
                'variants' => [
                    [
                        'name' => 'Box of 5 pieces (5kg each)',
                        'suffix' => '5PCS',
                        'quantity' => 5,
                        'price' => 7.500,
                        'stock' => 50,
                    ],
                ],
            ],
        ];
    }
}
