<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

final class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = $this->getAllProducts();

        foreach ($products as $productData) {
            $product = Product::create([
                'category_id' => $productData['category_id'],
                'slug' => Str::slug($productData['name_en']) . '-' . uniqid(),
                'sku' => $productData['sku'],
                'price' => $productData['price'],
                'compare_at_price' => $productData['compare_at_price'] ?? null,
                'cost' => round($productData['price'] * 0.6, 3),
                'current_stock' => $productData['stock'] ?? 100,
                'low_stock_threshold' => 10,
                'track_inventory' => true,
                'daily_production_capacity' => $productData['daily_capacity'] ?? 100,
                'lead_time_hours' => $productData['lead_time'] ?? 24,
                'is_available' => true,
                'is_featured' => $productData['is_featured'] ?? false,
                'is_taxable' => true,
                'requires_shipping' => true,
                'views_count' => 0,
                'sales_count' => 0,
            ]);

            // Add English translation
            $product->translations()->create([
                'locale' => 'en',
                'name' => $productData['name_en'],
                'short_description' => $productData['description_en'],
                'description' => $productData['description_en'],
            ]);

            // Add Arabic translation
            $product->translations()->create([
                'locale' => 'ar',
                'name' => $productData['name_ar'],
                'short_description' => $productData['description_ar'],
                'description' => $productData['description_ar'],
            ]);

            // Add placeholder images
            $product->images()->create([
                'image_url' => 'https://placehold.co/800x600/e8e8e8/666666?text=' . urlencode($productData['name_en']),
                'alt_text' => $productData['name_en'],
                'is_primary' => true,
                'sort_order' => 0,
            ]);

            // Add variants if specified
            if (isset($productData['variants']) && is_array($productData['variants'])) {
                foreach ($productData['variants'] as $index => $variantData) {
                    $product->variants()->create([
                        'name' => $variantData['name'],
                        'sku' => $product->sku . '-' . $variantData['suffix'],
                        'price' => $variantData['price'],
                        'stock' => $variantData['stock'] ?? 50,
                        'pack_quantity' => $variantData['quantity'],
                        'is_available' => true,
                        'sort_order' => $index,
                    ]);
                }
            }
        }

        $this->command->info('Products seeded: ' . count($products) . ' items with translations and variants (complete menu)');
    }

    private function getAllProducts(): array
    {
        return [
            // =====================================================
            // CATEGORY 2: Mini Size Croissants (30g)
            // =====================================================
            [
                'category_id' => 2,
                'name_en' => 'Mini Plain Croissant',
                'name_ar' => 'ميني كرواسون سادة',
                'description_en' => 'Mini plain croissant, 30g per piece. Classic French buttery croissant in mini size.',
                'description_ar' => 'ميني كرواسون سادة، 30 جرام للقطعة. كرواسون فرنسي كلاسيكي بالزبدة بحجم صغير.',
                'sku' => 'EB-MNPC-001',
                'price' => 3.000,
                'stock' => 150,
                'daily_capacity' => 500,
                'lead_time' => 24,
                'is_featured' => true,
            ],
            [
                'category_id' => 2,
                'name_en' => 'Mini Cheese Croissant',
                'name_ar' => 'ميني كرواسون جبن',
                'description_en' => 'Mini cheese croissant, 30g per piece. Filled with savory cheese.',
                'description_ar' => 'ميني كرواسون جبن، 30 جرام للقطعة. محشو بالجبن اللذيذ.',
                'sku' => 'EB-MNCC-002',
                'price' => 3.000,
                'stock' => 150,
                'daily_capacity' => 500,
                'lead_time' => 24,
                'is_featured' => true,
            ],
            [
                'category_id' => 2,
                'name_en' => 'Mini Almond Croissant',
                'name_ar' => 'ميني كرواسون لوز',
                'description_en' => 'Mini almond croissant, 30g per piece. Filled with premium almond cream.',
                'description_ar' => 'ميني كرواسون لوز، 30 جرام للقطعة. محشو بكريمة اللوز الفاخرة.',
                'sku' => 'EB-MNAC-003',
                'price' => 3.000,
                'stock' => 120,
                'daily_capacity' => 400,
                'lead_time' => 24,
                'is_featured' => false,
            ],
            [
                'category_id' => 2,
                'name_en' => 'Mini Zatar Croissant',
                'name_ar' => 'ميني كرواسون زعتر',
                'description_en' => 'Mini zatar croissant, 30g per piece. Traditional Middle Eastern flavor.',
                'description_ar' => 'ميني كرواسون زعتر، 30 جرام للقطعة. نكهة شرق أوسطية تقليدية.',
                'sku' => 'EB-MNZC-004',
                'price' => 3.000,
                'stock' => 150,
                'daily_capacity' => 500,
                'lead_time' => 24,
                'is_featured' => true,
            ],
            [
                'category_id' => 2,
                'name_en' => 'Mini Halloumi Croissant',
                'name_ar' => 'ميني كرواسون حلوم',
                'description_en' => 'Mini halloumi croissant, 30g per piece. Filled with authentic halloumi cheese.',
                'description_ar' => 'ميني كرواسون حلوم، 30 جرام للقطعة. محشو بجبنة الحلوم الأصلية.',
                'sku' => 'EB-MNHC-005',
                'price' => 3.000,
                'stock' => 130,
                'daily_capacity' => 450,
                'lead_time' => 24,
                'is_featured' => false,
            ],
            [
                'category_id' => 2,
                'name_en' => 'Mini Chocolate Bun',
                'name_ar' => 'ميني كرواسون شوكولاتة',
                'description_en' => 'Mini chocolate bun, 30g per piece. Filled with rich chocolate.',
                'description_ar' => 'ميني كرواسون شوكولاتة، 30 جرام للقطعة. محشو بالشوكولاتة الغنية.',
                'sku' => 'EB-MNCB-006',
                'price' => 3.000,
                'stock' => 150,
                'daily_capacity' => 500,
                'lead_time' => 24,
                'is_featured' => true,
            ],

            // =====================================================
            // CATEGORY 3: Medium Size Croissants (55g)
            // =====================================================
            [
                'category_id' => 3,
                'name_en' => 'Plain Croissant',
                'name_ar' => 'كرواسون سادة حجم متوسط',
                'description_en' => 'Plain croissant, 55g per piece. Classic French buttery croissant. 100 pieces per box.',
                'description_ar' => 'كرواسون سادة، 55 جرام للقطعة. كرواسون فرنسي كلاسيكي بالزبدة. 100 قطعة في الصندوق.',
                'sku' => 'EB-MDC-001',
                'price' => 12.500,
                'stock' => 20,
                'daily_capacity' => 50,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 100', 'suffix' => 'BOX', 'quantity' => 100, 'price' => 12.500, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 3,
                'name_en' => 'Cheese Croissant',
                'name_ar' => 'كرواسون جبن حجم متوسط',
                'description_en' => 'Cheese croissant, 55g per piece. Filled with savory cheese. 100 pieces per box.',
                'description_ar' => 'كرواسون جبن، 55 جرام للقطعة. محشو بالجبن اللذيذ. 100 قطعة في الصندوق.',
                'sku' => 'EB-MDCC-002',
                'price' => 13.500,
                'stock' => 20,
                'daily_capacity' => 50,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 100', 'suffix' => 'BOX', 'quantity' => 100, 'price' => 13.500, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 3,
                'name_en' => 'Brown Croissant',
                'name_ar' => 'كرواسون أسمر متوسط الحجم',
                'description_en' => 'Brown croissant, 55g per piece. Made with wholemeal flour. 100 pieces per box.',
                'description_ar' => 'كرواسون أسمر، 55 جرام للقطعة. مصنوع من دقيق القمح الكامل. 100 قطعة في الصندوق.',
                'sku' => 'EB-MDBC-003',
                'price' => 12.500,
                'stock' => 20,
                'daily_capacity' => 50,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 100', 'suffix' => 'BOX', 'quantity' => 100, 'price' => 12.500, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 3,
                'name_en' => 'Zatar Croissant',
                'name_ar' => 'كرواسون زعتر حجم متوسط',
                'description_en' => 'Zatar croissant, 55g per piece. Traditional Middle Eastern flavor. 100 pieces per box.',
                'description_ar' => 'كرواسون زعتر، 55 جرام للقطعة. نكهة شرق أوسطية تقليدية. 100 قطعة في الصندوق.',
                'sku' => 'EB-MDZC-004',
                'price' => 13.500,
                'stock' => 20,
                'daily_capacity' => 50,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 100', 'suffix' => 'BOX', 'quantity' => 100, 'price' => 13.500, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 3,
                'name_en' => 'Chocolate Bun',
                'name_ar' => 'كرواسون شوكولاتة حجم متوسط',
                'description_en' => 'Chocolate bun, 55g per piece. Filled with rich chocolate. 100 pieces per box.',
                'description_ar' => 'كرواسون شوكولاتة، 55 جرام للقطعة. محشو بالشوكولاتة الغنية. 100 قطعة في الصندوق.',
                'sku' => 'EB-MDCB-005',
                'price' => 13.500,
                'stock' => 20,
                'daily_capacity' => 50,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 100', 'suffix' => 'BOX', 'quantity' => 100, 'price' => 13.500, 'stock' => 20],
                ],
            ],

            // =====================================================
            // CATEGORY 4: Jumbo Size Croissants (120g)
            // =====================================================
            [
                'category_id' => 4,
                'name_en' => 'Jumbo Plain Croissant',
                'name_ar' => 'جامبو كرواسون سادة',
                'description_en' => 'Jumbo plain croissant, 120g per piece. Large classic French croissant. 50 pieces per box.',
                'description_ar' => 'جامبو كرواسون سادة، 120 جرام للقطعة. كرواسون فرنسي كبير. 50 قطعة في الصندوق.',
                'sku' => 'EB-JMC-001',
                'price' => 12.500,
                'stock' => 15,
                'daily_capacity' => 30,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 12.500, 'stock' => 15],
                ],
            ],
            [
                'category_id' => 4,
                'name_en' => 'Jumbo Cheese Croissant',
                'name_ar' => 'جامبو كرواسون جبن',
                'description_en' => 'Jumbo cheese croissant, 120g per piece. Filled with savory cheese. 50 pieces per box.',
                'description_ar' => 'جامبو كرواسون جبن، 120 جرام للقطعة. محشو بالجبن اللذيذ. 50 قطعة في الصندوق.',
                'sku' => 'EB-JMCC-002',
                'price' => 13.500,
                'stock' => 15,
                'daily_capacity' => 30,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 13.500, 'stock' => 15],
                ],
            ],
            [
                'category_id' => 4,
                'name_en' => 'Jumbo Almond Croissant',
                'name_ar' => 'جامبو كرواسون لوز',
                'description_en' => 'Jumbo almond croissant, 120g per piece. Filled with premium almond cream. 50 pieces per box.',
                'description_ar' => 'جامبو كرواسون لوز، 120 جرام للقطعة. محشو بكريمة اللوز الفاخرة. 50 قطعة في الصندوق.',
                'sku' => 'EB-JMAC-003',
                'price' => 22.500,
                'stock' => 10,
                'daily_capacity' => 20,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 22.500, 'stock' => 10],
                ],
            ],
            [
                'category_id' => 4,
                'name_en' => 'Jumbo Zatar Croissant',
                'name_ar' => 'جامبو كرواسون زعتر',
                'description_en' => 'Jumbo zatar croissant, 120g per piece. Traditional Middle Eastern flavor. 50 pieces per box.',
                'description_ar' => 'جامبو كرواسون زعتر، 120 جرام للقطعة. نكهة شرق أوسطية تقليدية. 50 قطعة في الصندوق.',
                'sku' => 'EB-JMZC-004',
                'price' => 13.500,
                'stock' => 15,
                'daily_capacity' => 30,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 13.500, 'stock' => 15],
                ],
            ],
            [
                'category_id' => 4,
                'name_en' => 'Jumbo Chocolate Bun',
                'name_ar' => 'جامبو كرواسون شوكولاتة',
                'description_en' => 'Jumbo chocolate bun, 120g per piece. Filled with rich chocolate. 50 pieces per box.',
                'description_ar' => 'جامبو كرواسون شوكولاتة، 120 جرام للقطعة. محشو بالشوكولاتة الغنية. 50 قطعة في الصندوق.',
                'sku' => 'EB-JMCB-005',
                'price' => 13.500,
                'stock' => 15,
                'daily_capacity' => 30,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 13.500, 'stock' => 15],
                ],
            ],

            // =====================================================
            // CATEGORY 5: Rolls & Danish
            // =====================================================
            [
                'category_id' => 5,
                'name_en' => 'Raisin Roll',
                'name_ar' => 'رولا الزبيب (عجينة كرواسون)',
                'description_en' => 'Raisin roll made with croissant dough, 70g per piece. 100 pieces per box.',
                'description_ar' => 'رولا الزبيب مصنوعة من عجينة الكرواسون، 70 جرام للقطعة. 100 قطعة في الصندوق.',
                'sku' => 'EB-RR-001',
                'price' => 13.500,
                'stock' => 20,
                'daily_capacity' => 40,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 100', 'suffix' => 'BOX', 'quantity' => 100, 'price' => 13.500, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 5,
                'name_en' => 'Chocolate Roll',
                'name_ar' => 'رولا الشوكولاتة (عجينة كرواسون)',
                'description_en' => 'Chocolate roll made with croissant dough, 70g per piece. 100 pieces per box.',
                'description_ar' => 'رولا الشوكولاتة مصنوعة من عجينة الكرواسون، 70 جرام للقطعة. 100 قطعة في الصندوق.',
                'sku' => 'EB-CR-002',
                'price' => 13.500,
                'stock' => 20,
                'daily_capacity' => 40,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 100', 'suffix' => 'BOX', 'quantity' => 100, 'price' => 13.500, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 5,
                'name_en' => 'Cinnamon & Walnuts Roll',
                'name_ar' => 'رولا القرفة والجوز (عجينة كرواسون)',
                'description_en' => 'Cinnamon and walnuts roll made with croissant dough, 70g per piece. 100 pieces per box.',
                'description_ar' => 'رولا القرفة والجوز مصنوعة من عجينة الكرواسون، 70 جرام للقطعة. 100 قطعة في الصندوق.',
                'sku' => 'EB-CWR-003',
                'price' => 18.000,
                'stock' => 15,
                'daily_capacity' => 30,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 100', 'suffix' => 'BOX', 'quantity' => 100, 'price' => 18.000, 'stock' => 15],
                ],
            ],
            [
                'category_id' => 5,
                'name_en' => 'Rectangular Danish',
                'name_ar' => 'عجينة دانش مستطيلة',
                'description_en' => 'Rectangular Danish pastry, 80g per piece. 100 pieces per box.',
                'description_ar' => 'عجينة دانش مستطيلة، 80 جرام للقطعة. 100 قطعة في الصندوق.',
                'sku' => 'EB-RD-004',
                'price' => 25.000,
                'stock' => 10,
                'daily_capacity' => 20,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 100', 'suffix' => 'BOX', 'quantity' => 100, 'price' => 25.000, 'stock' => 10],
                ],
            ],
            [
                'category_id' => 5,
                'name_en' => 'Danish',
                'name_ar' => 'عجينة دانش',
                'description_en' => 'Danish pastry, 80g per piece. 100 pieces per box.',
                'description_ar' => 'عجينة دانش، 80 جرام للقطعة. 100 قطعة في الصندوق.',
                'sku' => 'EB-D-005',
                'price' => 25.000,
                'stock' => 10,
                'daily_capacity' => 20,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 100', 'suffix' => 'BOX', 'quantity' => 100, 'price' => 25.000, 'stock' => 10],
                ],
            ],

            // =====================================================
            // CATEGORY 6: Cookies Dough (55g)
            // =====================================================
            [
                'category_id' => 6,
                'name_en' => 'Walnuts Chocolate Cookies Dough',
                'name_ar' => 'عجينة كوكيز الشوكولاتة والجوز',
                'description_en' => 'Walnuts chocolate cookies dough, 55g per piece. Ready to bake. 50 pieces per box.',
                'description_ar' => 'عجينة كوكيز الشوكولاتة والجوز، 55 جرام للقطعة. جاهزة للخبز. 50 قطعة في الصندوق.',
                'sku' => 'EB-WCC-001',
                'price' => 10.000,
                'stock' => 25,
                'daily_capacity' => 60,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 10.000, 'stock' => 25],
                ],
            ],
            [
                'category_id' => 6,
                'name_en' => 'Pistachio Chocolate Cookies Dough',
                'name_ar' => 'عجينة كوكيز بالفستق والشوكولاتة',
                'description_en' => 'Pistachio chocolate cookies dough, 55g per piece. Ready to bake. 50 pieces per box.',
                'description_ar' => 'عجينة كوكيز بالفستق والشوكولاتة، 55 جرام للقطعة. جاهزة للخبز. 50 قطعة في الصندوق.',
                'sku' => 'EB-PCC-002',
                'price' => 12.500,
                'stock' => 20,
                'daily_capacity' => 50,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 12.500, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 6,
                'name_en' => 'Double Chocolate Cookies Dough',
                'name_ar' => 'عجينة كوكيز بالشوكولاتة المزدوجة',
                'description_en' => 'Double chocolate cookies dough, 55g per piece. Ready to bake. 50 pieces per box.',
                'description_ar' => 'عجينة كوكيز بالشوكولاتة المزدوجة، 55 جرام للقطعة. جاهزة للخبز. 50 قطعة في الصندوق.',
                'sku' => 'EB-DCC-003',
                'price' => 12.500,
                'stock' => 20,
                'daily_capacity' => 50,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 12.500, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 6,
                'name_en' => 'Peanut Butter Cookies Dough',
                'name_ar' => 'عجينة كوكيز زبدة الفول السوداني',
                'description_en' => 'Peanut butter cookies dough, 55g per piece. Ready to bake. 50 pieces per box.',
                'description_ar' => 'عجينة كوكيز زبدة الفول السوداني، 55 جرام للقطعة. جاهزة للخبز. 50 قطعة في الصندوق.',
                'sku' => 'EB-PBC-004',
                'price' => 10.000,
                'stock' => 25,
                'daily_capacity' => 60,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 10.000, 'stock' => 25],
                ],
            ],

            // =====================================================
            // CATEGORY 7: Muffins & Babka
            // =====================================================
            [
                'category_id' => 7,
                'name_en' => 'Vanilla Muffin',
                'name_ar' => 'مافن الفانيليا',
                'description_en' => 'Vanilla muffin, 140g per piece. 50 pieces per box.',
                'description_ar' => 'مافن الفانيليا، 140 جرام للقطعة. 50 قطعة في الصندوق.',
                'sku' => 'EB-VM-001',
                'price' => 10.500,
                'stock' => 20,
                'daily_capacity' => 40,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 10.500, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 7,
                'name_en' => 'Chocolate Muffin',
                'name_ar' => 'مافن الشوكولاتة',
                'description_en' => 'Chocolate muffin, 140g per piece. 50 pieces per box.',
                'description_ar' => 'مافن الشوكولاتة، 140 جرام للقطعة. 50 قطعة في الصندوق.',
                'sku' => 'EB-CM-002',
                'price' => 10.500,
                'stock' => 20,
                'daily_capacity' => 40,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 10.500, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 7,
                'name_en' => 'Blueberry Muffin',
                'name_ar' => 'مافن التوت الأزرق',
                'description_en' => 'Blueberry muffin, 140g per piece. 50 pieces per box.',
                'description_ar' => 'مافن التوت الأزرق، 140 جرام للقطعة. 50 قطعة في الصندوق.',
                'sku' => 'EB-BM-003',
                'price' => 11.500,
                'stock' => 20,
                'daily_capacity' => 40,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 11.500, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 7,
                'name_en' => 'Cinnamon Babka',
                'name_ar' => 'بابكا القرفة',
                'description_en' => 'Cinnamon babka, 300g per piece. Traditional Eastern European sweet bread.',
                'description_ar' => 'بابكا القرفة، 300 جرام للقطعة. خبز حلو تقليدي من أوروبا الشرقية.',
                'sku' => 'EB-CB-004',
                'price' => 1.000,
                'stock' => 50,
                'daily_capacity' => 100,
                'lead_time' => 24,
                'is_featured' => true,
            ],
            [
                'category_id' => 7,
                'name_en' => 'Zatar Babka',
                'name_ar' => 'بابكا بالزعتر',
                'description_en' => 'Zatar babka, 300g per piece. Savory babka with Middle Eastern herbs.',
                'description_ar' => 'بابكا بالزعتر، 300 جرام للقطعة. بابكا مالحة بأعشاب الشرق الأوسط.',
                'sku' => 'EB-ZB-005',
                'price' => 1.000,
                'stock' => 50,
                'daily_capacity' => 100,
                'lead_time' => 24,
                'is_featured' => false,
            ],
            [
                'category_id' => 7,
                'name_en' => 'Cheese Olive Babka',
                'name_ar' => 'بابكا بالجبن والزيتون',
                'description_en' => 'Cheese and olive babka, 300g per piece. Savory babka with cheese and olives.',
                'description_ar' => 'بابكا بالجبن والزيتون، 300 جرام للقطعة. بابكا مالحة بالجبن والزيتون.',
                'sku' => 'EB-COB-006',
                'price' => 1.200,
                'stock' => 40,
                'daily_capacity' => 80,
                'lead_time' => 24,
                'is_featured' => true,
            ],

            // =====================================================
            // CATEGORY 8: Sourdough Breads (900g)
            // =====================================================
            [
                'category_id' => 8,
                'name_en' => 'White Sourdough',
                'name_ar' => 'خبز ساوردو أبيض',
                'description_en' => 'White sourdough bread with natural yeast, 900g per loaf. 7 pieces per box.',
                'description_ar' => 'خبز ساوردو أبيض بالخميرة الطبيعية، 900 جرام للرغيف. 7 قطع في الصندوق.',
                'sku' => 'EB-WS-001',
                'price' => 0.900,
                'stock' => 40,
                'daily_capacity' => 80,
                'lead_time' => 48,
                'is_featured' => true,
            ],
            [
                'category_id' => 8,
                'name_en' => 'Norlander Sourdough',
                'name_ar' => 'خبز نورلندر ساوردو',
                'description_en' => 'Norlander sourdough bread with natural yeast, 900g per loaf. 7 pieces per box.',
                'description_ar' => 'خبز نورلندر ساوردو بالخميرة الطبيعية، 900 جرام للرغيف. 7 قطع في الصندوق.',
                'sku' => 'EB-NS-002',
                'price' => 1.200,
                'stock' => 30,
                'daily_capacity' => 60,
                'lead_time' => 48,
                'is_featured' => true,
            ],
            [
                'category_id' => 8,
                'name_en' => 'Rye Sourdough',
                'name_ar' => 'ساوردو حبوب الجاودار',
                'description_en' => 'Rye sourdough bread with natural yeast, 900g per loaf. 7 pieces per box.',
                'description_ar' => 'ساوردو حبوب الجاودار بالخميرة الطبيعية، 900 جرام للرغيف. 7 قطع في الصندوق.',
                'sku' => 'EB-RS-003',
                'price' => 1.200,
                'stock' => 30,
                'daily_capacity' => 60,
                'lead_time' => 48,
                'is_featured' => false,
            ],
            [
                'category_id' => 8,
                'name_en' => 'Wholemeal Sourdough',
                'name_ar' => 'خبز ساوردو كامل الحبوب',
                'description_en' => 'Wholemeal sourdough bread with natural yeast, 900g per loaf. 7 pieces per box.',
                'description_ar' => 'خبز ساوردو كامل الحبوب بالخميرة الطبيعية، 900 جرام للرغيف. 7 قطع في الصندوق.',
                'sku' => 'EB-WMS-004',
                'price' => 1.200,
                'stock' => 30,
                'daily_capacity' => 60,
                'lead_time' => 48,
                'is_featured' => true,
            ],
            [
                'category_id' => 8,
                'name_en' => 'Multi Sourdough',
                'name_ar' => 'خبز الساوردو متعدد الحبوب',
                'description_en' => 'Multi-grain sourdough bread with natural yeast, 900g per loaf. 7 pieces per box.',
                'description_ar' => 'خبز الساوردو متعدد الحبوب بالخميرة الطبيعية، 900 جرام للرغيف. 7 قطع في الصندوق.',
                'sku' => 'EB-MS-005',
                'price' => 1.500,
                'stock' => 25,
                'daily_capacity' => 50,
                'lead_time' => 48,
                'is_featured' => true,
            ],
            [
                'category_id' => 8,
                'name_en' => 'Moringa Sourdough',
                'name_ar' => 'خبز ساوردو مورينجا',
                'description_en' => 'Moringa sourdough bread with natural yeast, 900g per loaf. 7 pieces per box.',
                'description_ar' => 'خبز ساوردو مورينجا بالخميرة الطبيعية، 900 جرام للرغيف. 7 قطع في الصندوق.',
                'sku' => 'EB-MOS-006',
                'price' => 1.500,
                'stock' => 20,
                'daily_capacity' => 40,
                'lead_time' => 48,
                'is_featured' => true,
            ],

            // =====================================================
            // CATEGORY 9: Ready Baked Breads
            // =====================================================
            // Samoon Bread
            [
                'category_id' => 9,
                'name_en' => 'White Samoon Bread',
                'name_ar' => 'خبز صمون أبيض',
                'description_en' => 'White samoon bread, 70g per piece. 50 pieces per box.',
                'description_ar' => 'خبز صمون أبيض، 70 جرام للقطعة. 50 قطعة في الصندوق.',
                'sku' => 'EB-WSB-001',
                'price' => 2.000,
                'stock' => 30,
                'daily_capacity' => 100,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 2.000, 'stock' => 30],
                ],
            ],
            [
                'category_id' => 9,
                'name_en' => 'Brown Samoon Bread',
                'name_ar' => 'خبز صمون أسمر',
                'description_en' => 'Brown samoon bread, 70g per piece. 50 pieces per box.',
                'description_ar' => 'خبز صمون أسمر، 70 جرام للقطعة. 50 قطعة في الصندوق.',
                'sku' => 'EB-BSB-002',
                'price' => 2.500,
                'stock' => 30,
                'daily_capacity' => 100,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 2.500, 'stock' => 30],
                ],
            ],
            [
                'category_id' => 9,
                'name_en' => 'Sesame Samoon Bread',
                'name_ar' => 'خبز صمون بالسمسم',
                'description_en' => 'Sesame samoon bread, 70g per piece. 50 pieces per box.',
                'description_ar' => 'خبز صمون بالسمسم، 70 جرام للقطعة. 50 قطعة في الصندوق.',
                'sku' => 'EB-SSB-003',
                'price' => 2.500,
                'stock' => 30,
                'daily_capacity' => 100,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 2.500, 'stock' => 30],
                ],
            ],
            // Pavé Multigrain
            [
                'category_id' => 9,
                'name_en' => 'Pavé Multigrain',
                'name_ar' => 'خبز بافي متعدد الحبوب',
                'description_en' => 'Pavé multigrain bread, 150g per piece. 60 pieces per box.',
                'description_ar' => 'خبز بافي متعدد الحبوب، 150 جرام للقطعة. 60 قطعة في الصندوق.',
                'sku' => 'EB-PM-004',
                'price' => 7.200,
                'stock' => 25,
                'daily_capacity' => 80,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 60', 'suffix' => 'BOX', 'quantity' => 60, 'price' => 7.200, 'stock' => 25],
                ],
            ],
            // Panini Bread
            [
                'category_id' => 9,
                'name_en' => 'Brown Panini Bread',
                'name_ar' => 'خبز بانيني أسمر',
                'description_en' => 'Brown panini bread. 50 pieces per box.',
                'description_ar' => 'خبز بانيني أسمر. 50 قطعة في الصندوق.',
                'sku' => 'EB-BPN-005',
                'price' => 9.500,
                'stock' => 20,
                'daily_capacity' => 60,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 9.500, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 9,
                'name_en' => 'White Panini Bread',
                'name_ar' => 'خبز بانيني أبيض',
                'description_en' => 'White panini bread. 50 pieces per box.',
                'description_ar' => 'خبز بانيني أبيض. 50 قطعة في الصندوق.',
                'sku' => 'EB-WPN-006',
                'price' => 9.500,
                'stock' => 20,
                'daily_capacity' => 60,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 9.500, 'stock' => 20],
                ],
            ],

            // =====================================================
            // CATEGORY 10: Half Baked Breads
            // =====================================================
            // Artisan Bread
            [
                'category_id' => 10,
                'name_en' => 'Dejuenette Bread',
                'name_ar' => 'خبز دوجونيت',
                'description_en' => 'Dejuenette artisan bread, 100g per piece. Half baked, ready to finish at home. 50 pieces per box.',
                'description_ar' => 'خبز دوجونيت حرفي، 100 جرام للقطعة. نصف مخبوز، جاهز للتشطيب في المنزل. 50 قطعة في الصندوق.',
                'sku' => 'EB-DJ-001',
                'price' => 3.000,
                'stock' => 25,
                'daily_capacity' => 70,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 3.000, 'stock' => 25],
                ],
            ],
            [
                'category_id' => 10,
                'name_en' => 'Vienoise Bread',
                'name_ar' => 'خبز فيينواز',
                'description_en' => 'Vienoise artisan bread, 100g per piece. Half baked, ready to finish at home. 50 pieces per box.',
                'description_ar' => 'خبز فيينواز حرفي، 100 جرام للقطعة. نصف مخبوز، جاهز للتشطيب في المنزل. 50 قطعة في الصندوق.',
                'sku' => 'EB-VN-002',
                'price' => 5.000,
                'stock' => 20,
                'daily_capacity' => 60,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 5.000, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 10,
                'name_en' => 'Portuguese Bread',
                'name_ar' => 'خبز برتغالي',
                'description_en' => 'Portuguese artisan bread, 55g per piece. Half baked, ready to finish at home. 50 pieces per box.',
                'description_ar' => 'خبز برتغالي حرفي، 55 جرام للقطعة. نصف مخبوز، جاهز للتشطيب في المنزل. 50 قطعة في الصندوق.',
                'sku' => 'EB-PT-003',
                'price' => 3.000,
                'stock' => 25,
                'daily_capacity' => 70,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 50', 'suffix' => 'BOX', 'quantity' => 50, 'price' => 3.000, 'stock' => 25],
                ],
            ],
            // Baguettes
            [
                'category_id' => 10,
                'name_en' => 'French Baguette',
                'name_ar' => 'خبز باغيت فرنسي',
                'description_en' => 'French baguette. Half baked, ready to finish at home. 10 pieces per box.',
                'description_ar' => 'خبز باغيت فرنسي. نصف مخبوز، جاهز للتشطيب في المنزل. 10 قطع في الصندوق.',
                'sku' => 'EB-FB-004',
                'price' => 2.300,
                'stock' => 30,
                'daily_capacity' => 80,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 10', 'suffix' => 'BOX', 'quantity' => 10, 'price' => 2.300, 'stock' => 30],
                ],
            ],
            [
                'category_id' => 10,
                'name_en' => 'Sesame Baguette',
                'name_ar' => 'خبز باغيت فرنسي بالسمسم',
                'description_en' => 'French baguette with sesame. Half baked, ready to finish at home. 10 pieces per box.',
                'description_ar' => 'خبز باغيت فرنسي بالسمسم. نصف مخبوز، جاهز للتشطيب في المنزل. 10 قطع في الصندوق.',
                'sku' => 'EB-SB-005',
                'price' => 2.300,
                'stock' => 30,
                'daily_capacity' => 80,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 10', 'suffix' => 'BOX', 'quantity' => 10, 'price' => 2.300, 'stock' => 30],
                ],
            ],
            [
                'category_id' => 10,
                'name_en' => 'Country Baguette',
                'name_ar' => 'خبز باغيت الريفي',
                'description_en' => 'Country baguette. Half baked, ready to finish at home. 10 pieces per box.',
                'description_ar' => 'خبز باغيت الريفي. نصف مخبوز، جاهز للتشطيب في المنزل. 10 قطع في الصندوق.',
                'sku' => 'EB-CB-006',
                'price' => 2.600,
                'stock' => 25,
                'daily_capacity' => 70,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 10', 'suffix' => 'BOX', 'quantity' => 10, 'price' => 2.600, 'stock' => 25],
                ],
            ],

            // =====================================================
            // CATEGORY 11: Burger Buns
            // =====================================================
            // Large Buns (100g)
            [
                'category_id' => 11,
                'name_en' => 'Burger Plain Buns (100g)',
                'name_ar' => 'خبز برغر سادة',
                'description_en' => 'Plain burger buns, 100g per piece. 60 pieces per box.',
                'description_ar' => 'خبز برغر سادة، 100 جرام للقطعة. 60 قطعة في الصندوق.',
                'sku' => 'EB-BPB100-001',
                'price' => 4.800,
                'stock' => 25,
                'daily_capacity' => 80,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 60', 'suffix' => 'BOX', 'quantity' => 60, 'price' => 4.800, 'stock' => 25],
                ],
            ],
            [
                'category_id' => 11,
                'name_en' => 'Burger Sesame Buns (100g)',
                'name_ar' => 'خبز برغر بالسمسم',
                'description_en' => 'Sesame burger buns, 100g per piece. 60 pieces per box.',
                'description_ar' => 'خبز برغر بالسمسم، 100 جرام للقطعة. 60 قطعة في الصندوق.',
                'sku' => 'EB-BSB100-002',
                'price' => 4.800,
                'stock' => 25,
                'daily_capacity' => 80,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 60', 'suffix' => 'BOX', 'quantity' => 60, 'price' => 4.800, 'stock' => 25],
                ],
            ],
            // Regular Buns (70g)
            [
                'category_id' => 11,
                'name_en' => 'Burger White Buns (70g)',
                'name_ar' => 'خبز برغر أبيض',
                'description_en' => 'White burger buns, 70g per piece. 60 pieces per box.',
                'description_ar' => 'خبز برغر أبيض، 70 جرام للقطعة. 60 قطعة في الصندوق.',
                'sku' => 'EB-BWB-003',
                'price' => 3.600,
                'stock' => 25,
                'daily_capacity' => 80,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 60', 'suffix' => 'BOX', 'quantity' => 60, 'price' => 3.600, 'stock' => 25],
                ],
            ],
            [
                'category_id' => 11,
                'name_en' => 'Burger Sesame Buns (70g)',
                'name_ar' => 'خبز برغر بالسمسم',
                'description_en' => 'Sesame burger buns, 70g per piece. 60 pieces per box.',
                'description_ar' => 'خبز برغر بالسمسم، 70 جرام للقطعة. 60 قطعة في الصندوق.',
                'sku' => 'EB-BSB70-004',
                'price' => 3.600,
                'stock' => 25,
                'daily_capacity' => 80,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 60', 'suffix' => 'BOX', 'quantity' => 60, 'price' => 3.600, 'stock' => 25],
                ],
            ],
            [
                'category_id' => 11,
                'name_en' => 'Brown Burger Buns',
                'name_ar' => 'خبز برغر أسمر',
                'description_en' => 'Brown burger buns, 70g per piece. 60 pieces per box.',
                'description_ar' => 'خبز برغر أسمر، 70 جرام للقطعة. 60 قطعة في الصندوق.',
                'sku' => 'EB-BBB-005',
                'price' => 3.600,
                'stock' => 25,
                'daily_capacity' => 80,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 60', 'suffix' => 'BOX', 'quantity' => 60, 'price' => 3.600, 'stock' => 25],
                ],
            ],
            [
                'category_id' => 11,
                'name_en' => 'Potato Buns',
                'name_ar' => 'خبز برغر البطاطا',
                'description_en' => 'Potato burger buns, 70g per piece. 60 pieces per box.',
                'description_ar' => 'خبز برغر البطاطا، 70 جرام للقطعة. 60 قطعة في الصندوق.',
                'sku' => 'EB-PBB-006',
                'price' => 4.800,
                'stock' => 20,
                'daily_capacity' => 60,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 60', 'suffix' => 'BOX', 'quantity' => 60, 'price' => 4.800, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 11,
                'name_en' => 'Brioche Buns',
                'name_ar' => 'خبز برغر بريوش',
                'description_en' => 'Brioche burger buns, 70g per piece. 60 pieces per box.',
                'description_ar' => 'خبز برغر بريوش، 70 جرام للقطعة. 60 قطعة في الصندوق.',
                'sku' => 'EB-BRIB-007',
                'price' => 12.000,
                'stock' => 15,
                'daily_capacity' => 40,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 60', 'suffix' => 'BOX', 'quantity' => 60, 'price' => 12.000, 'stock' => 15],
                ],
            ],
            // Mini Buns (30g)
            [
                'category_id' => 11,
                'name_en' => 'Mini Burger Sesame Buns',
                'name_ar' => 'خبز برغر بالسمسم صغير',
                'description_en' => 'Mini sesame burger buns, 30g per piece. 160 pieces per box.',
                'description_ar' => 'خبز برغر بالسمسم صغير، 30 جرام للقطعة. 160 قطعة في الصندوق.',
                'sku' => 'EB-MBSB-008',
                'price' => 7.200,
                'stock' => 20,
                'daily_capacity' => 100,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 160', 'suffix' => 'BOX', 'quantity' => 160, 'price' => 7.200, 'stock' => 20],
                ],
            ],

            // =====================================================
            // CATEGORY 12: Slice Breads
            // =====================================================
            // Classic Slice Bread
            [
                'category_id' => 12,
                'name_en' => 'White Slice',
                'name_ar' => 'خبز توست أبيض',
                'description_en' => 'White sliced bread, 450g per loaf. 15 pieces per box.',
                'description_ar' => 'خبز توست أبيض، 450 جرام للرغيف. 15 قطعة في الصندوق.',
                'sku' => 'EB-WSL-001',
                'price' => 7.500,
                'stock' => 20,
                'daily_capacity' => 50,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 15', 'suffix' => 'BOX', 'quantity' => 15, 'price' => 7.500, 'stock' => 20],
                ],
            ],
            [
                'category_id' => 12,
                'name_en' => 'Brown Slice',
                'name_ar' => 'خبز توست أسمر',
                'description_en' => 'Brown sliced bread, 450g per loaf. 15 pieces per box.',
                'description_ar' => 'خبز توست أسمر، 450 جرام للرغيف. 15 قطعة في الصندوق.',
                'sku' => 'EB-BSL-002',
                'price' => 9.000,
                'stock' => 20,
                'daily_capacity' => 50,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 15', 'suffix' => 'BOX', 'quantity' => 15, 'price' => 9.000, 'stock' => 20],
                ],
            ],
            // Specialty Slice Bread
            [
                'category_id' => 12,
                'name_en' => 'Chia Slice',
                'name_ar' => 'خبز توست بذور الشيا',
                'description_en' => 'Chia seed sliced bread, 450g per loaf. 15 pieces per box.',
                'description_ar' => 'خبز توست بذور الشيا، 450 جرام للرغيف. 15 قطعة في الصندوق.',
                'sku' => 'EB-CSL-003',
                'price' => 10.500,
                'stock' => 15,
                'daily_capacity' => 40,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 15', 'suffix' => 'BOX', 'quantity' => 15, 'price' => 10.500, 'stock' => 15],
                ],
            ],
            [
                'category_id' => 12,
                'name_en' => 'Oats Slice',
                'name_ar' => 'خبز توست بالشوفان',
                'description_en' => 'Oats sliced bread, 450g per loaf. 15 pieces per box.',
                'description_ar' => 'خبز توست بالشوفان، 450 جرام للرغيف. 15 قطعة في الصندوق.',
                'sku' => 'EB-OSL-004',
                'price' => 10.500,
                'stock' => 15,
                'daily_capacity' => 40,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 15', 'suffix' => 'BOX', 'quantity' => 15, 'price' => 10.500, 'stock' => 15],
                ],
            ],
            [
                'category_id' => 12,
                'name_en' => 'Pumpkin Seeds Slice',
                'name_ar' => 'خبز توست بذور اليقطين',
                'description_en' => 'Pumpkin seed sliced bread, 450g per loaf. 15 pieces per box.',
                'description_ar' => 'خبز توست بذور اليقطين، 450 جرام للرغيف. 15 قطعة في الصندوق.',
                'sku' => 'EB-PSL-005',
                'price' => 10.500,
                'stock' => 15,
                'daily_capacity' => 40,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 15', 'suffix' => 'BOX', 'quantity' => 15, 'price' => 10.500, 'stock' => 15],
                ],
            ],
            [
                'category_id' => 12,
                'name_en' => 'Mix Seeds Slice',
                'name_ar' => 'خبز توست ببذور مشكلة',
                'description_en' => 'Mixed seeds sliced bread, 450g per loaf. 15 pieces per box.',
                'description_ar' => 'خبز توست ببذور مشكلة، 450 جرام للرغيف. 15 قطعة في الصندوق.',
                'sku' => 'EB-MSL-006',
                'price' => 10.500,
                'stock' => 15,
                'daily_capacity' => 40,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 15', 'suffix' => 'BOX', 'quantity' => 15, 'price' => 10.500, 'stock' => 15],
                ],
            ],
            [
                'category_id' => 12,
                'name_en' => 'Flax Seeds Slice',
                'name_ar' => 'خبز توست ببذور الكتان',
                'description_en' => 'Flax seed sliced bread, 450g per loaf. 15 pieces per box.',
                'description_ar' => 'خبز توست ببذور الكتان، 450 جرام للرغيف. 15 قطعة في الصندوق.',
                'sku' => 'EB-FSL-007',
                'price' => 10.500,
                'stock' => 15,
                'daily_capacity' => 40,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 15', 'suffix' => 'BOX', 'quantity' => 15, 'price' => 10.500, 'stock' => 15],
                ],
            ],
            [
                'category_id' => 12,
                'name_en' => 'Sunflower Slice',
                'name_ar' => 'خبز توست ببذور دوار الشمس',
                'description_en' => 'Sunflower seed sliced bread, 450g per loaf. 15 pieces per box.',
                'description_ar' => 'خبز توست ببذور دوار الشمس، 450 جرام للرغيف. 15 قطعة في الصندوق.',
                'sku' => 'EB-SSL-008',
                'price' => 10.500,
                'stock' => 15,
                'daily_capacity' => 40,
                'lead_time' => 24,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 15', 'suffix' => 'BOX', 'quantity' => 15, 'price' => 10.500, 'stock' => 15],
                ],
            ],
            [
                'category_id' => 12,
                'name_en' => 'Sesame Slice',
                'name_ar' => 'خبز توست السمسم',
                'description_en' => 'Sesame sliced bread, 450g per loaf. 15 pieces per box.',
                'description_ar' => 'خبز توست السمسم، 450 جرام للرغيف. 15 قطعة في الصندوق.',
                'sku' => 'EB-SESL-009',
                'price' => 10.500,
                'stock' => 15,
                'daily_capacity' => 40,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 15', 'suffix' => 'BOX', 'quantity' => 15, 'price' => 10.500, 'stock' => 15],
                ],
            ],
            [
                'category_id' => 12,
                'name_en' => 'Brioche Slice',
                'name_ar' => 'خبز بريوش',
                'description_en' => 'Brioche sliced bread, 450g per loaf. 15 pieces per box.',
                'description_ar' => 'خبز بريوش، 450 جرام للرغيف. 15 قطعة في الصندوق.',
                'sku' => 'EB-BRISL-010',
                'price' => 10.500,
                'stock' => 15,
                'daily_capacity' => 40,
                'lead_time' => 24,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 15', 'suffix' => 'BOX', 'quantity' => 15, 'price' => 10.500, 'stock' => 15],
                ],
            ],

            // =====================================================
            // CATEGORY 13: Paton Dough
            // =====================================================
            [
                'category_id' => 13,
                'name_en' => 'Pie Base',
                'name_ar' => 'قاعدة فطيرة',
                'description_en' => 'Pie base dough, 5000g per piece. Professional raw dough ready to shape. 5 pieces per box.',
                'description_ar' => 'قاعدة فطيرة، 5000 جرام للقطعة. عجينة خام احترافية جاهزة للتشكيل. 5 قطع في الصندوق.',
                'sku' => 'EB-PB-001',
                'price' => 7.500,
                'stock' => 15,
                'daily_capacity' => 30,
                'lead_time' => 48,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 5', 'suffix' => 'BOX', 'quantity' => 5, 'price' => 7.500, 'stock' => 15],
                ],
            ],
            [
                'category_id' => 13,
                'name_en' => 'Croissant Paton',
                'name_ar' => 'عجينة باتون كرواسون',
                'description_en' => 'Croissant paton dough, 9600g per piece. Professional laminated dough. 2 pieces per box.',
                'description_ar' => 'عجينة باتون كرواسون، 9600 جرام للقطعة. عجينة مطبقة احترافية. 2 قطعة في الصندوق.',
                'sku' => 'EB-CP-002',
                'price' => 20.000,
                'stock' => 10,
                'daily_capacity' => 20,
                'lead_time' => 48,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 2', 'suffix' => 'BOX', 'quantity' => 2, 'price' => 20.000, 'stock' => 10],
                ],
            ],
            [
                'category_id' => 13,
                'name_en' => 'Pastry Sheet',
                'name_ar' => 'رقائق الفطائر',
                'description_en' => 'Pastry sheet dough, 8000g per piece. Professional raw dough ready to shape. 1 piece per box.',
                'description_ar' => 'رقائق الفطائر، 8000 جرام للقطعة. عجينة خام احترافية جاهزة للتشكيل. قطعة واحدة في الصندوق.',
                'sku' => 'EB-PS-003',
                'price' => 17.000,
                'stock' => 12,
                'daily_capacity' => 25,
                'lead_time' => 48,
                'is_featured' => true,
                'variants' => [
                    ['name' => 'Box of 1', 'suffix' => 'BOX', 'quantity' => 1, 'price' => 17.000, 'stock' => 12],
                ],
            ],
            [
                'category_id' => 13,
                'name_en' => 'Paton of Puff',
                'name_ar' => 'باتون بف باستري',
                'description_en' => 'Puff pastry paton, 5500g per piece. Professional puff pastry dough. 2 pieces per box.',
                'description_ar' => 'باتون بف باستري، 5500 جرام للقطعة. عجينة بف باستري احترافية. 2 قطعة في الصندوق.',
                'sku' => 'EB-PP-004',
                'price' => 15.000,
                'stock' => 12,
                'daily_capacity' => 25,
                'lead_time' => 48,
                'is_featured' => false,
                'variants' => [
                    ['name' => 'Box of 2', 'suffix' => 'BOX', 'quantity' => 2, 'price' => 15.000, 'stock' => 12],
                ],
            ],
        ];
    }
}
